= Welcome to our Integration Guide
:page-layout: tiles

This documentation aims at product owners, project managers and developers that want to make themselves familiar with the Nexeed Industrial Application System (IAS) integration and development topic.
You will find an overarching guide that helps you through the whole decision and integration process.
Besides the Integration Guide, you will also find the developer documentations for all relevant Nexeed Industrial Application System modules to go into more detail.

// intro
[.tile]
[.bosch-ic-home]
--
[.title]
Introduction & Building blocks
[.text]
Get an introduction about what the Nexeed Industrial Application System is, what it is composed of and what it can help you with
[.link]
xref:introduction:introduction.adoc[] | xref:buildingblocks:buildingblocks.adoc[]
--

// concepts
[.tile]
[.bosch-ic-artificial-intelligence]
--
[.title]
Concepts
[.text]
Self Contained Systems, Iframes, Kubernetes - everything that you might need to know about how the system was designed and how it works
[.link]
xref:concepts:general.adoc[Concepts]
--

// getting started
[.tile]
[.bosch-ic-plane-start]
--
[.title]
Getting started
[.text]
Get an overview about the work packages needed and learn how to prepare for your integration journey

[.link]
xref:gettingStarted:gettingStarted.adoc[Getting started]
--

// Guide
[.tile]
[.bosch-ic-format-checklist]
--
[.title]
Milestones & Roadmap
[.text]


Develop your application with this step-by-step guide to achieve full integration

[.link]
xref:goals:roadmap.adoc[]
--

Get to know our *Core Services*:

//IDB
[.tile]
[.bosch-ic-barcode]
--
[.title]
ID Builder

[.text]
Developer documentation of our ID Builder

[.link]
xref:IDB:introduction:introduction.adoc[Documentation]  | xref:IDB:api:api.adoc[API]
--

//SMDP
[.tile]
[.bosch-ic-health-warning]
--
[.title]
Deviation Processor

[.text]
Developer documentation of our Deviation Processor

[.link]
xref:SMDP:introduction:introduction.adoc[Documentation]  | xref:SMDP:api:api.adoc[API]
--

// MACMA
[.tile]
[.bosch-ic-security-user]
--
[.title]
Multitenant Access Control

[.text]
Developer documentation of our authentication and authorization tool

[.link]
xref:MACMA:01_introduction:introduction.adoc[Documentation] | xref:MACMA:api:api.adoc[API]
--

//NOISE
[.tile]
[.bosch-ic-notification-arrow]
--
[.title]
Notification Service

[.text]
Developer documentation of our Notification Service

[.link]
xref:NOISE:introduction:introduction.adoc[Documentation]  | xref:NOISE:api:api.adoc[API]
--


//Ticket Management
[.tile]
[.bosch-ic-ticket]
--
[.title]
Ticket Management
[.text]
Developer documentation of our Ticket Management module

[.link]
xref:TM:01_introduction:00_introduction.adoc[Documentation]  | xref:TM:api:api.adoc[API]
--




//Portal
[.tile]
[.bosch-ic-ui]
--
[.title]
Web Portal

[.text]
Developer documentation of our central user facing module

[.link]
xref:Portal::index.adoc[Documentation] | xref:Portal:api:api.adoc[API]
--



Learn how to integrate with our *Shopfloor Management* modules to enhance your production transparency and informed decision-making:
//Shopfloor Management

[.tile]
[.bosch-ic-world-pin]
--
[.title]
Global Production Overview

[.text]
Developer documentation of our Global Production Overview service

[.link]
xref:GPO:01_introduction:introduction.adoc[Documentation]  | xref:GPO:api:api.adoc[API]
--

[.tile]
[.bosch-ic-chart-bar-arrow]
--
[.title]
Shopfloor Management Essentials

[.text]
Developer documentation of our Shopfloor Management Essentials modules Shift Book, KPI Reporting, Andon Live, Administration and ConfigBridge

[.link]
xref:shopfloor-management-essentials:introduction:introduction.adoc[Documentation]  | xref:shopfloor-management-essentials:api:index.adoc[API]
--


Learn how you can build upon our *Product & Quality* modules to help you improve production processes and part quality:

//Product Setup Management
[.tile]
[.bosch-ic-settings-arrows]
--
[.title]
Product Setup Management
[.text]
Developer documentation of our Product Setup Management module

[.link]
xref:PSM:introduction:introduction.adoc[Documentation]  | xref:PSM:api:api.adoc[API]
--

//PartTraceability
[.tile]
[.bosch-ic-hierarchy-search]
--
[.title]
Part Traceability

[.text]
Central hub for manufacturing quality data.

[.link]
xref:PT:introduction:introduction.adoc[Documentation] |
xref:PT:api:data-browser-api.adoc[APIs]
--

//Process Quality
[.tile]
[.bosch-ic-chart-average]
--
[.title]
Process Quality

[.text]
Centralized and process-agnostic monitoring of production processes (incl. automated anomaly detection).

[.link]
xref:process_quality:introduction:introduction.adoc[Documentation] |
xref:process_quality:api:api.adoc[API]
--

//Setup Specs
[.tile]
[.bosch-ic-settings-arrows]
--
[.title]
Setup Specs
[.text]
Developer documentation of our Setup Specs module

[.link]
xref:SPECS:introduction:introduction.adoc[Documentation]  | xref:SPECS:api:api.adoc[API]
--


Learn how to integrate with our *Execution* modules to manage your production orders more easily:


//LineControl
[.tile]
[.bosch-ic-line-arrow-checkmark]
--
[.title]
LineControl
[.text]
Developer documentation of our LineControl module

[.link]
xref:LC:introduction:introduction.adoc[Documentation] | xref:LC:api:lineasm.adoc[API]
--

//Material Management
[.tile]
[.bosch-ic-material]
--
[.title]
Material Management
[.text]
Developer documentation of our Material Management module

[.link]
xref:MAT:introduction:introduction.adoc[Documentation]  | xref:MAT:api:api.adoc[API]
--

//Order Management
[.tile]
[.bosch-ic-sequence-checkmark]
--
[.title]
Order Management
[.text]
Developer documentation of our Order Management module

[.link]
xref:OM:introduction:introduction.adoc[Documentation]  | xref:OM:api:asyncapi.adoc[Event API]
--

Learn how our *Intralogistics* modules can help you optimize your warehouse processes:

//Transport- and Stockmanagement
[.tile]
[.bosch-ic-fork-lift]
--
[.title]
Transport- and Stockmanagement

[.text]
Developer documentation of our Transport- and Stockmanagement services

[.link]
xref:IL:introduction:introduction.adoc[Introduction] | xref:IL:api:communication_hub_api.adoc[APIs]
--

////
//AGV Control Center
[.tile]
[.bosch-ic-autobod]
--
[.title]
AGV Control Center

[.text]
Developer documentation of our AGV Control Center service

[.link]
 xref:AGV:api:api.adoc[API]
--
////

Learn how you can build upon our *Machine & Equipment* modules to help you minimize downtimes and improve production performance:

//DevicePortal
[.tile]
[.bosch-ic-devices]
--
[.title]
Device Portal

[.text]
Complete documentation of our Device Portal offering

[.link]
https://documentation-automation.bosch-nexeed.com/DevicePortal/#/index/en/en[Documentation,window=_blank,role="extLink secured"]  | https://portal.bosch-nexeed.com/dp/solution/apidoc/index.html[Solution API,window=_blank,role="extLink"] | https://portal.bosch-nexeed.com/dp/device/apidoc/index.html[Device API,window=_blank,role="extLink"]
--

//Condition Monitoring
[.tile]
[.bosch-ic-analysis]
--
[.title]
Condition Monitoring
[.text]
Permanent status recording of machines and systems for maximum transparency

[.link]
xref:CM:01_introduction:00_introduction.adoc[Documentation] | xref:CM:90_api:cm_api.adoc[API]
--

//Maintenance Management
[.tile]
[.bosch-ic-configuration]
--
[.title]
Maintenance Management

[.text]
Developer documentation of our Maintenance Management Service

[.link]
xref:MM:introduction:introduction.adoc[Documentation]  | xref:MM:api:mm_api.adoc[API]
--

//Tool Management
[.tile]
[.bosch-ic-wrench-cloud]
--
[.title]
Tool Management
[.text]
Developer documentation of the Tool Management service

[.link]
xref:tool_management:introduction:introduction.adoc[Documentation] | xref:tool_management:introduction:introduction.adoc[API]
--

Learn about our *Enterprise & Shopfloor Integration* services:

//Archiving Bridge
[.tile]
[.bosch-ic-box-archive]
--
[.title]
Archiving Bridge

[.text]
Developer documentation for Archiving Bridge service.

[.link]
xref:ArchivingBridge:introduction:introduction.adoc[Documentation]  | xref:ArchivingBridge:api:api.adoc[API]
--

//ERP Connectivity
[.tile]
[.bosch-ic-connectivity]
--
[.title]
ERP Connectivity

[.text]
Developer documentation of our ERP Connectivity service

[.link]
xref:erp_connectivity:introduction:introduction.adoc[Documentation] | xref:erp_connectivity:api:api.adoc[API]
--

//DataPublisher
[.tile]
[.bosch-ic-cloud-upload]
--
[.title]
Data Publisher

[.text]
Developer documentation of our Data Publisher service

[.link]
xref:DataPublisher:introduction:introduction.adoc[Documentation]  | xref:DataPublisher:api:api.adoc[API]
--

//Information Router
[.tile]
[.bosch-ic-connectivity]
--
[.title]
Information Router

[.text]
Developer documentation of our connectivity services

[.link]
xref:IR:01_introduction:00_introduction.adoc[Documentation] | xref:IR:90_api:api.adoc[API]
--


// MDM
[.tile]
[.bosch-ic-hierarchy]
--
[.title]
Master Data Management

[.text]
Developer documentation of our master data management tool

[.link]
xref:master_data_management:introduction:introduction.adoc[Documentation]  | xref:master_data_management:api:equipment.adoc[APIs]
--


//Orchestrator
[.tile]
[.bosch-ic-survey-checkmark]
--
[.title]
Orchestrator

[.text]
Developer documentation of our Orchestrator service

[.link]
xref:Orchestrator:introduction:index.adoc[Documentation]
--
