name: $(Build.DefinitionName)_$(Date:yyyyMMdd)_$(Rev:r)

trigger:
  - "master"

stages:
  - stage: PreRelease
    jobs:
      - job: build_and_PR_integration_guide
        displayName: Build and PR Integration Guide
        pool: LinuxAgents-Cloud-VM
        variables:
          - group: integration-guide-variable-group
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            path: master
          - bash: |
              cd ../master
              export GIT_CREDENTIALS='https://$(System.AccessToken):@dev.azure.com'
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              rm -rf .cache/antora
              rm -rf build
              echo "Running 'npm install' with node $(node --version) and npm $(npm --version)"
              npm install
              docker run -d -p 8000:8000 --name kroki yuzutech/kroki
              ./node_modules/@antora/cli/bin/antora --stacktrace generate --url=https://delightful-pond-0b8657103-prerelease.westeurope.5.azurestaticapps.net site.yml
            displayName: Build documentation for check
          - bash: |
              cd ../master
              cp -f -r src/docs/html/* build/site/
              cp -f src/docs/staticwebapp.config.json build/site/
            displayName: Move files to build
          - task: AzureStaticWebApp@0
            inputs:
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_INTEGRATION_GUIDE)
              ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
              # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
              workingDirectory: "$(Agent.BuildDirectory)/master"
              app_location: "/build/site" # App source code path
              api_location: "/api" # Api source code path - optional
              output_location: "" # Built app content directory - optional
              production_branch: 'release'
              deployment_environment: 'prerelease'
              ###### End of Repository/Build Configurations ######
          - bash: |
              sudo apt install python3-bs4 python3-dnspython python3-requests
              pip3 install linkchecker
              cd build/site/
              PATH=$PATH:/home/AzDevOps/.local/bin
              linkchecker --check-extern --no-warnings --ignore-url='devicebridge.bosch.com' --ignore-url='video.bosch.com' --ignore-url='example' --ignore-url='boschdevcloud' --ignore-url='localhost:4200' --ignore-url='documentation-automation' "https://delightful-pond-0b8657103-prerelease.westeurope.5.azurestaticapps.net"
            displayName: Run Linkchecker
          - bash: |
              cd ../master
              export GIT_CREDENTIALS='https://$(System.AccessToken):@dev.azure.com'
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              rm -rf .cache/antora
              rm -rf build
              echo "Running 'npm install' with node $(node --version) and npm $(npm --version)"
              npm install
              ./node_modules/@antora/cli/bin/antora --stacktrace generate site.yml
            displayName: Build documentation for release
          - bash: |
              cd ../master
              cp -f -r src/docs/html/* build/site/
              cp -f src/docs/staticwebapp.config.json build/site/
            displayName: Move files to build
          - checkout: git://integration-guide@release
            persistCredentials: true
            path: release
          - bash: |
              cd ../release
              git config --global user.email "bci.dev-admin@bcn.bosch.com"
              git config --global user.name "BCI Azure Build Agent"
              git checkout -b release-request/$(Build.Buildnumber)
              cp -f -r ../master/build .
              git add -A
              git commit -m "new build files from commit $(Build.SourceVersionMessage)"
              git push --set-upstream origin release-request/$(Build.Buildnumber)
            displayName: Git branch & push
          - bash: |
              cd ../release
              echo $(System.AccessToken) | az devops login
              az repos pr create --auto-complete true --detect true --repository integration-guide --delete-source-branch true --source-branch release-request/$(Build.Buildnumber) --target-branch release --description "Preview Link: https://delightful-pond-0b8657103-prerelease.westeurope.5.azurestaticapps.net/ \n Antora output: $ANTORA_LOG"
            displayName: Git create PR
          - bash: |
              docker rm --force kroki
              sudo chown -R AzDevOps $(Agent.BuildDirectory)
            condition: always()
            displayName: Cleanup