site:
  title: Nexeed Documentations
  url: https://learn.bosch-nexeed.com/
  start_page: IASIG::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: src/docs
    # START MACMA components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/macma-module/
      start_paths: [src/docs/00_common, src/docs/50_developer-guide, src/docs/99_glossary]
      tags: [ 'documentation-to-publish/{1..9}.{32..99}.*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/macma-core/
      start_path: src/main/antora
      tags: [  'documentation-to-publish/{1..9}.{32..99}.*']
      version:
        documentation-to-publish/(*): $1
      branches: ~
    # END MACMA components
    # START Portal components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/nexeed-portal-docs
      start_paths: [src/docs/50_developer-guide, src/docs/99_glossary]
      branches: [ 'documentation-to-publish/{5..9}.{20..99}','documentation-to-publish/{6..9}.{0..99}' ]
      version:
        documentation-to-publish/(*): $1
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/nexeed-portal-backend
      start_paths: [ src/Bosch.Nexeed.WebPortal.CoreService/AntoraApiDoc ]
      branches: [ 'release/{5..9}.{20..99}.x', 'release/{6..9}.{0..99}.x']
      version:
        release/(*).x: $1
    # END Portal components
    # START NOISE components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/notification-service
      start_paths: [ src/docs/50_developer-documentation ]
      branches: [ 'release/1.{26..69}.x','release/{2..69}.{0..69}.x' ]
      version:
        release/(*).x: $1
    # END NOISE components
    # START SMDP components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/nexeed-deviation-processor-backend
      start_paths: [ docs/50_developer-documentation ]
      branches: [ 'support/1.{8..69}.x','support/{2..69}.{0..69}.x' ]
      version:
        support/(*).x: $1
    # END SMDP components
    # START IDB components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/id-builder-docs
      start_paths: [ src/docs/50_developer-documentation ]
      branches: [ 'release/3.{5..69}.x','release/{4..69}.{0..69}.x' ]
      version:
        release/(*).x: $1
    # END IDB components
    # START MDM components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/mdm-opsmanual
      start_paths: [ src/docs/50_developer-documentation, src/docs/99_glossary]
      branches: [ 'release/v8.{4..9}.{0..9}','release/v{9..99}.{0..9}.{0..9}' ]
      version:
        release/v(*): $1
    # END MDM components
    # START IR components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/ir-module
      start_paths: [src/docs/50_developer-guide, src/docs/99_glossary]
      branches: [ 'releases/antora/1.7' ]
      version:
        releases/antora/(*): $1
    # END IR components
    # START Orchestrator components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/orchestrator-service
      start_paths: [ docs/src/50_developer-guide, docs/src/99_glossary ]
      tags: [ 'documentation-to-publish/*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    # END Orchestrator
    # START Data Publisher
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/datapublisher
      start_paths: [ src/docs/50_developer-guide , src/docs/99_glossary ]
      tags: [ 'documentation-to-publish/*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    # END Data Publisher
    # START TM components
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/tm-module/
      start_paths: [ src/docs/00_common, src/docs/50_developer-guides ]
      tags: [ 'documentation-to-publish/*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/ticket-management/
      start_path: ticket-service-backend/src/main/antora
      tags: [ 'documentation-to-publish/*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    # END TM components
    # START Archiving Bridge
    - url: https://dev.azure.com/bosch-bci/Nx_PQ/_git/archivingbridge
      start_paths: [ docs/50_developer-guides]
      #tags: [ 'documentation-to-publish/*' ]
      version: "1.0.0"
    #    documentation-to-publish/(*): $1
      branches: "fix/rest_api_docu_page"
    # END Archiving Bridge
    # START SMC components
    - url: https://dev.azure.com/bosch-bci/Nx_SM/_git/scs-shopfloor-management-essentials
      start_paths: [ docs/50_developer-documentation ]
      branches: [ 'master' ]
      version: 'latest'
    - url: https://dev.azure.com/bosch-bci/Nx_SM/_git/pdamda-global-production-overview
      start_paths: [ docs/50_developer-documentation ]
      branches: [ 'support/5.6.x', 'support/5.7.x' ]
      version:
        support/(*).x: $1
    # END SMC components
    # START OM Components
    - url: https://dev.azure.com/bosch-bci/Nx_EX/_git/ordermanagement-services
      start_paths: [src/docs/50_developer-documentation]
      branches: ['release/5.{7..99}','release/{6..99}.{0..99}']
      version:
        release/(*): $1
    # END OM components
    # START LC Components
    - url: https://dev.azure.com/bosch-bci/Nx_EX/_git/ias-linecontrol-ui-service
      start_paths: [src/docs/50_developer-documentation]
      tags: [ 'documentation-to-publish/*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    # END LC components
    # START CM components
    - url: https://dev.azure.com/bosch-bci/Nx_ME/_git/condition-monitoring
      start_paths: [ documentation/module-documentation/src/docs/50_developer-guides ]
      tags: [ 'documentation-to-publish/*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    # END CM components
    # START IL components
    - url: https://dev.azure.com/bosch-bci/Nx_IES/_git/ies-services
      start_paths: [ src/docs/50_developer-documentation ]
      tags: [ 'documentation-to-publish/*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    # END IL components
    # START MAT Components
    - url: https://dev.azure.com/bosch-bci/Nx_EX/_git/matcontrol-docs
      start_paths: [src/docs/50_developer-documentation,src/docs/99_glossary]
      branches: ['release/3.{7..99}','release/{4..9}.{0..99}']
      version:
        release/(*): $1
    # END MAT components
    # START MM Components
    - url: https://dev.azure.com/bosch-bci/Nx_ME/_git/ias-module-repo-mm
      start_paths: [src/docs/50_developer-documentation,src/docs/99_glossary]
    #  branches: ['support/1.{6..99}.x','support/{2..99}.{0..99}.x']
      branches: ['support/1.6.x']
      version:
        support/(*).x: $1
    # END MM components
    # START TOMA Components
    - url: https://dev.azure.com/bosch-bci/Nx_ME/_git/toolmanagement
      start_paths: [ src/docs/50_developer-documentation,src/docs/99_glossary ]
      branches: [ 'release/v2.{7..99}.x', 'release/v{3..99}.{0..99}.x' ]
      version:
        release/v(*).x: $1
    # END TOMA components
    # START PSM components
    - url: https://dev.azure.com/bosch-bci/Nx_PQ/_git/productsetupmanagement-docs
      start_paths: [src/docs/50_developer-documentation]
      branches: ['support/V3.{8..99}.x', 'support/V{4..99}.{0..99}.x' ]
      version:
        support/V(*).x: $1
    # END PSM components
    # START SPECS Components
    - url: https://dev.azure.com/bosch-bci/Nx_PQ/_git/setupcontrol-services
      start_paths: [src/docs/50_developer-documentation]
      branches: ['support/release-1.{5..99}.{0..99}','support/release-{2..99}.{0..99}.{0..99}']
      version:
        support/release-(*): $1
    # END SPECS components
    # START ERP Connectivity
    - url: https://dev.azure.com/bosch-bci/Nx_Foundation/_git/ias-erpconnectivity
      start_paths: [ src/docs/50_developer-documentation , src/docs/99_glossary ]
      tags: [ 'documentation-to-publish/*' ]
      version:
        documentation-to-publish/(*): $1
      branches: ~
    # END ERP Connectivity
    # START PT components
    - url: https://dev.azure.com/bosch-bci/Nx_PQ/_git/traceability-docs
      start_paths: [ src/docs/50_developer-documentation ]
      branches: [ 'release/2.{4..99}.x','release/{3..99}.{0..99}.x' ]
      version:
        release/(*).x: $1
    # END PT components
    # START PQM components
    - url: https://dev.azure.com/bosch-bci/Nx_PQ/_git/trinity-monorepo
      start_paths: [ docs/module-documentation/src/docs/50_developer-documentation ]
      branches: [ 'release/3.{7..99}.x','release/{4..99}.{0..99}.x' ]
      version:
        release/(*).x: $1
    # END PQM components
git:
  ensure_git_suffix: false
  fetch_concurrency: 1
ui:
  bundle:
    url: ./docs-ui/ui-bundle.zip
    snapshot: true
runtime:
  cache_dir: ./.cache/antora
output:
  clean: true
antora:
  extensions:
    - require: "@antora/lunr-extension"
      index_latest_only: true
asciidoc:
  attributes:
    doctype: book
    page-component-sort-order:
    - area: IASIG
    - area: Core Services
      components: IDB,SMDP,MACMA,NOISE,TM,Portal
    - area: Shopfloor Management
      components: GPO,shopfloor-management-essentials
    - area: Machine & Equipment
      components: CM,tool_management,MM
    - area: Product & Quality
      components: PSM,PT,process_quality,SPECS
    - area: Execution
      components: LC,MAT,OM
    - area: Intralogistics
      components: IL
    - area: Machine & Equipment
      components: CM,MM
    - area: Enterprise & Shopfloor Integration
      components: ArchivingBridge,erp_connectivity,DataPublisher,IR,master_data_management,Orchestrator
    kroki-fetch-diagram: true
    kroki-server-url: http://localhost:8000
  extensions:
    - asciidoctor-kroki
urls:
  latest_version_segment: ''