[[ConventionsConstraints]]
= Conventions & Constraints

This section explains common design and implementation conventions that we established over the years developing NEXEED modules. It shall serve as a guideline and not all aspects are strict requirements.

== General functional conventions

=== Portfolio integration

1. For user management, authentication and authorization, all applications MUST integrate with Nexeed Multitenant Access Control system .
+
This enables seamless security, user experience and common permissions.

2. For handling master data of shared entities, all applications SHOULD integrate with Nexeed Master Data Management.
+
This enables interoperability between applications and improves user acceptance. Master data that has not to be shared MUST be handled by the application within itself.

3. For interfacing with users, UIs MUST be integrated into Nexeed Web Portal.
+
This enables seamless user interaction and SSO.

4. For shop floor data integration, modules SHOULD integrate with Nexeed Integration Router.
+
This enables a slim architecture with central solving of common challenges.

5. For informing or alerting users or systems with notifications, modules SHOULD use the Nexeed Notification Service.
+
This enables a central configuration and implementation of common challenges.

6. For integrating into ERP work-loads, modules MUST integrate with our Nexeed ERP Connectivity module.
+
This

7. For configuring and handling of reporting processes, modules SHOULD use our Nexeed Reporting Management module.
+
This

8. For allowing integration into common data request flows, modules SHOULD integrate into Nexeed Orchestrator.
+
This

9. For integration into larger software environments, modules SHOULD integrate into Nexeed Data Publisher.
+
This

10. For sending data into archiving systems, modules SHOULD integrate into Nexeed Archiving Bridge.
+
This

=== Lifecycle

1. Modules SHOULD handle migrations of data stored in files or databases independently and transactional.

2. APIs SHOULD have to have their own lifecycle management in place. See our section on REST API lifecycles.

=== Multi-Tenancy

1. Modules SHOULD be multi-tenant capable. This means they should be able to securely receive, store and provide information from/to multiple tenants.
+
If modules are in an environment, where this is not necessary or can be achieved by other means, like horizontal scaling + configuration, implementation of this can be omitted.

== General non-functional conventions

1. Module design SHOULD be oriented around the https://12factor.net[12 factors] for service oriented software development.
2. Modules SHOULD implement caches, retries and lazy binding in order to become robust to behave correctly in a difficult environment.
3. Modules SHOULD be stateless to be scalable so that they can cope with change in load on the system.
4. Modules SHOULD implement transactional data handling to be reliable so that no data is lost when working on it.
5. Modules MUST implement SSL on data transport level to not allow threads to harm the data integrity.
6. Modules MUST NOT store security relevant data in code or configuration files but use encrypted storage mechanisms.

== Architecture conventions

1. Modules MUST be designed around the Self Contained Systems concept.
2. Modules SHOULD employ microservices. If you want to know how we have sliced our applications, you are very welcomed to contact our experts.
3. Modules MUST employ synchronous communication with other modules for time-critical data exchange through HTTPS REST requests.
4. Modules MUST employ asynchronous communication with other modules for non-time-critical data exchange through publish/subscribe by implementing AMQP 0.9.


== Environment conventions
=== Caching
1. Modules SHOULD use a dedicated application for sharing key/value pairs between services. In Bosch, REDIS is currently set as solution.

=== Messaging
1. Modules SHOULD NOT directly communicate with external message brokers. Modules SHOULD use the Nexeed Data Publisher for outbound communication and the Nexeed Information Router for inbound communication.
2. Modules SHOULD share events of their own use-cases as

=== Databases



== API conventions

Use Auth for all APIS

=== Decide between public and private APIs

TODO

=== Use REST for your APIs

TODO

=== Document your public APIs
Teams creating a Rest API should use OpenAPI to generate an up-to-date documentation.

About OpenAPI:

    The OpenAPI Specification, originally known as the Swagger Specification, is a specification for machine-readable interface files for describing, producing, consuming, and visualizing RESTful web services. A variety of tools can generate code, documentation and test cases given an interface file. Development of the OpenAPI Specification (OAS) is overseen by the Open API Initiative, an open source collaborative project of the Linux Foundation.

https://en.wikipedia.org/wiki/OpenAPI_Specification

OpenAPI has evolved from the Swagger tooling. Multiple companies have joined the initiative and help making this an accepted standard. OpenAPI can be used for specification-first approach of documentation. Swagger tooling also provides the possibility to do implementation-first approach.

Decided to be a preferred standard see 2018-05-04 OpenApi as Preferred Standard for REST API Documentation


TODO:
OpenAPI format
    IDs
    Schemata
    Examples
    Descriptions
Versioning
Provisioning
    make file available in Web Portal
    make file available in your module (swagger ws)
API should be documented directly in the source code (e.g. by using JAX-RS annotations) or nearby the source code

== User interface conventions

=== Wording
=== Internationalization
Each component as part of Nexeed IAS must provide the ability to support multiple languages in the user interface so that users in different markets can work easily with the module.
At least the languages German (de-DE) and English (en-US) have to be supported. Further languages depend on the market languages the module is released to.

Note: The translation process should preferably be automated (see How to automate your translation process on Azure DevOps), but this is no mandatory requirement regarding the QG rating.

Continuous Verification:
The translations themselves are checked and provided by the Technical Author.

Scope: All modules have to support at least English (en-US) and German (de-DE). Further language support depends on the needs of the target markets.


=== Styling
Style Guide
(Web Core)

=== Skinning
=== Experience
=== Performance

== Quality conventions

== Operations and Delivery

* the module provides his services as a docker image to Support Multiple Environments
* the provides docker image are built on top of BCI Docker Base Image
* the docker images are deployed to BCI Azure Container Registry
* the name of docker image fulfils the Docker Image Naming Conventions
* the version of the docker images fulfils the Docker Image Versioning Conventions
* the module is able to run behind reverse-proxy and on a defined content path (e.g. /mib-module) as described in SCSs and Reverse Proxy.
* the module is configurable by using environmental variables (no configuration files will be provided on a target execution environment)
* the environment variables fulfil the Environment Variable Conventions
* the defined databases and messaging protocols are supported (if module need it)

=== Docker Image Naming
https://inside-docupedia.bosch.com/confluence/display/NXP/Docker+Image+Naming+Conventions

=== Docker Image Versioning
https://inside-docupedia.bosch.com/confluence/display/NXP/Docker+Image+Versioning+Conventions

=== Environment Variables
https://inside-docupedia.bosch.com/confluence/display/NXP/Environment+Variable+Conventions
[…]
=== Namespaces
=== Logging
https://inside-docupedia.bosch.com/confluence/display/NXP/Logging+Guidelines?focusedCommentId=3814978244#comment-3814978244

=== Metrics

=== Database
https://inside-docupedia.bosch.com/confluence/display/NXP/Relational+Database+Conventions

== Coding conventions

https://inside-docupedia.bosch.com/confluence/display/NXP/Code+Quality+Standards

